version: "3.9"

networks:
    localdev:
        name: localdev

services:
    api:
        build: .
        restart: always
        ports:
            - "5252:80"
        networks:
            - localdev
